# Generated by Django 2.1.14 on 2019-11-29 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('ctyid', models.AutoField(db_column='ctyId', primary_key=True, serialize=False)),
                ('ctyname', models.CharField(db_column='ctyName', max_length=20, unique=True)),
                ('ctystate', models.CharField(db_column='ctyState', max_length=2)),
                ('ctyzipcode', models.CharField(db_column='ctyZipcode', max_length=5)),
                ('ctypopulation', models.IntegerField(blank=True, db_column='ctyPopulation', null=True)),
                ('ctycrimerate', models.DecimalField(blank=True, db_column='ctyCrimeRate', decimal_places=6, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'City',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('cmtid', models.AutoField(db_column='cmtId', primary_key=True, serialize=False)),
                ('cmtname', models.CharField(db_column='cmtName', max_length=64)),
                ('cmtlatitude', models.DecimalField(blank=True, db_column='cmtLatitude', decimal_places=7, max_digits=10, null=True)),
                ('cmtlongitude', models.DecimalField(blank=True, db_column='cmtLongitude', decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Community',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Googleuser',
            fields=[
                ('usrid', models.AutoField(db_column='usrId', primary_key=True, serialize=False)),
                ('usrname', models.CharField(blank=True, db_column='usrName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'GoogleUser',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('grcid', models.AutoField(db_column='grcId', primary_key=True, serialize=False)),
                ('grcdescription', models.CharField(blank=True, db_column='grcDescription', max_length=30, null=True)),
                ('grctype', models.SmallIntegerField(blank=True, db_column='grcType', null=True)),
                ('grclatitude', models.DecimalField(blank=True, db_column='grcLatitude', decimal_places=7, max_digits=10, null=True)),
                ('grclongitude', models.DecimalField(blank=True, db_column='grcLongitude', decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Grocery',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('rsdid', models.AutoField(db_column='rsdId', primary_key=True, serialize=False)),
                ('rsddescription', models.CharField(blank=True, db_column='rsdDescription', max_length=12, null=True)),
                ('rsdsqft', models.IntegerField(blank=True, db_column='rsdSqFt', null=True)),
                ('rsdbedroom', models.SmallIntegerField(blank=True, db_column='rsdBedroom', null=True)),
                ('rsdbathroom', models.SmallIntegerField(blank=True, db_column='rsdBathroom', null=True)),
                ('rsdprice', models.DecimalField(blank=True, db_column='rsdPrice', decimal_places=2, max_digits=8, null=True)),
                ('rsdtype', models.CharField(blank=True, db_column='rsdType', max_length=20, null=True)),
                ('rsdyearbuilt', models.IntegerField(blank=True, db_column='rsdYearBuilt', null=True)),
                ('cmtid', models.ForeignKey(db_column='cmtId', on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Community')),
            ],
            options={
                'db_table': 'Residence',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rvwid', models.AutoField(db_column='rvwId', primary_key=True, serialize=False)),
                ('rvwdate', models.DateTimeField(blank=True, db_column='rvwDate', null=True)),
                ('rvwrate', models.SmallIntegerField(blank=True, db_column='rvwRate', null=True)),
                ('rvwdescription', models.CharField(blank=True, db_column='rvwDescription', max_length=4096, null=True)),
                ('cmtid', models.ForeignKey(db_column='cmtId', on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Community')),
                ('usrid', models.ForeignKey(db_column='usrId', on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Googleuser')),
            ],
            options={
                'db_table': 'Review',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stpid', models.AutoField(db_column='stpId', primary_key=True, serialize=False)),
                ('cmtid', models.ForeignKey(db_column='cmtId', on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Community')),
            ],
            options={
                'db_table': 'Stop',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('sttid', models.AutoField(db_column='sttId', primary_key=True, serialize=False)),
                ('sttname', models.CharField(blank=True, db_column='sttName', max_length=30, null=True)),
                ('ctyid', models.ForeignKey(db_column='ctyId', on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.City')),
            ],
            options={
                'db_table': 'Street',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('trnid', models.AutoField(db_column='trnId', primary_key=True, serialize=False)),
                ('trndescription', models.CharField(blank=True, db_column='trnDescription', max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'Transportation',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='stop',
            name='trnid',
            field=models.ForeignKey(db_column='trnId', on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Transportation'),
        ),
        migrations.AddField(
            model_name='grocery',
            name='sttid',
            field=models.ForeignKey(db_column='sttId', on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Street'),
        ),
        migrations.AddField(
            model_name='community',
            name='sttid',
            field=models.ForeignKey(db_column='sttId', on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Street'),
        ),
        migrations.AlterUniqueTogether(
            name='stop',
            unique_together={('stpid', 'trnid', 'cmtid')},
        ),
    ]
